### ISSUE TITLE
for interfaceAF2predict.py

### ISSUE THREAD

**Issue by jongseo-park** [nrbennet/dl_binder_design#1]
Hi,

thank you for your useful repository.

In the interfaceAF2predict.py, in line 480,

I think `with open (checkpoint_filename, 'a') as f:` is missing.

sincerely,

jongseo

**Comment by Lyang556** [comment]
I think jongseo is right.

**Comment by nrbennet** [comment]
Thanks for letting me know about this! I just fixed it.
