### ISSUE TITLE
issue with silentfrompdbs

### ISSUE THREAD

**Issue by JA-Hull** [nrbennet/dl_binder_design#13]
In case anybody else runs into the issue where silentfrompdbs gives the following error:

basic.io.database: [ WARNING ] Unable to locate database file chemical/residue_type_sets/fa_standard/residue_types//home/bcov/from/jason/H3i.am1bcc.fa.mm.params

This appears to be the result of somebody hard coding a path that probably worked on the development machine. This appears to be an old issue seen in other deployments of RossettaFold (https://www.rosettacommons.org/node/11552). Changing the original line 53 from:

$jd2_program -l $tmp_list -out:file:silent $tmp_file -out:file:silent_struct_type binary -extra_res_fa /home/bcov/from/jason/H3i.am1bcc.fa.mm.params 1>&2
to:
$jd2_program -l $tmp_list -out:file:silent $tmp_file -out:file:silent_struct_type binary 

Seems to allow the program to complete, but I'm not sure of the potential downstream ramifications of this change.

**Comment by nrbennet** [comment]
Thank you for finding this bug. This has been corrected in the PR today
