### ISSUE TITLE
Fixing residues of binder chain in ProteinMPNN

### ISSUE THREAD

**Issue by alllirik** [nrbennet/dl_binder_design#15]
Hello! 

I am using motif scaffolding in RFdiffusion to incorporate binding motif into de novo scaffold, however, it seems that ProteinMPNN does not fix the motif sequence and redesigns it. Is there an argument for fixing residues by number? 

I've checked `dl_interface_design.py` for arguments, but only found "-fix_FIXED_res" for residues labeled as "FIXED" (in pdb, i guess), but I don't understand where this label would come from.

Thank you!

**Comment by nrbennet** [comment]
There is now a script that takes RFdiffusion trb files and adds the 'FIXED' labels to the pdbs. This is now described at the end of the README.
