### ISSUE TITLE
For dl_interface_design.py

### ISSUE THREAD

**Issue by Lyang556** [nrbennet/dl_binder_design#2]
Hi,

I tried to use the dl_interface_design.py to design new sequences for my binder, and i accept the warning like these

'core.chemical.AtomICoor: [ WARNING ] IcoorAtomID::atom_id(): Cannot get atom_id for POLYMER_LOWER of residue LEU 72.  Returning BOGUS ID instead.'

'core.conformation.Residue: [ WARNING ] missing an atom: 72  H   that depends on a nonexistent polymer connection! '

Is this normal?

sincerely,

Lei yang

**Comment by nrbennet** [comment]
This is normal, and you can ignore it. I will probably mute these warnings in the future.
