### ISSUE TITLE
pyjd2 in silentfrompdb

### ISSUE THREAD

**Issue by youngh81** [nrbennet/dl_binder_design#20]
Hi, I am trying to use silentfrompdbs in silent_tool, however, an error appeared as following:

./include/silent_tools/silentfrompdbs: line 51: pyjd2: command not found
./include/silent_tools/silentfrompdbs: line 53: silentls: command not found
./include/silent_tools/silentfrompdbs: line 53: silentrename: command not found
rm: cannot remove 'tmp_4T902UGUZSohZ.silent': No such file or directory
rm: cannot remove 'tmp_4T902UGUZSohZ.silent.idx': No such file or directory

It seems that the pyjd2 did not work or find in silentfrompdbs script, any suggestions is appreciated. thanks.

**Comment by youngh81** [comment]
Problem was fixed,thanks

**Comment by partrita** [comment]
> Problem was fixed,thanks

I got same problem, how did you fix it?

```
silentfrompdbs: line 51: pyjd2: command not found
silentfrompdbs: line 53: silentls: command not found
silentfrompdbs: line 53: silentrename: command not found
rm: cannot remove 'tmp_IHQEXzbWkHY91.silent': No such file or directory
rm: cannot remove 'tmp_IHQEXzbWkHY91.silent.idx': No such file or directory
```

**Comment by fsmalik** [comment]
You should go into the script and put a "./" before pyjd2, silentls, and silentrename. I think they are defined in variables at the top of the script.
