### ISSUE TITLE
Why can't GPU be used for inference?

### ISSUE THREAD

**Issue by aw10279** [nrbennet/dl_binder_design#24]
When I run interfaceAF2predict.py and dl_interface_design.py to make inferences, I found only CPU being used. I'm sure the cuda has been installed by .yml file and  GPU works fine in other programs. So how can I use my GPU for inference?

**Comment by nrbennet** [comment]
I have added test scripts next to the environment .yml files that will test whether the environment has been correctly installed and can use the GPU you have. If you are having issues with this you may need to change the CUDA version that is being installed in the environment.
