### ISSUE TITLE
How to set seqs_per_struct >=2 when relax_cycles =1 ?

### ISSUE THREAD

**Issue by Samuel-gwb** [nrbennet/dl_binder_design#27]
Hi, very great work! And also great for sharing method !
I have one question that it seems that seqs_per_struct must be 1 if relax_cycles > 0, defined in dl_interface_design.py.
How to implement seqs_per_struct >=2 when relax is allowed ?

**Comment by youngh81** [comment]
-relax_cyle 5

**Comment by Samuel-gwb** [comment]
> -relax_cyle 5

Many thanks !

**Comment by nrbennet** [comment]
Having seqs_per_struct > 1 and relax_cycles > 0 is not currently enabled. This combination can lead to a combinatorial explosion in the number of Rosetta relax trajectories which are performed so I just do not allow it. This check is pretty easy to turn off in the code though if you're keen to take off the training wheels.
