### ISSUE TITLE
tensorflow 2.12.1 requires jax>=0.3.15

### ISSUE THREAD

**Issue by frankligy** [nrbennet/dl_binder_design#31]
Hello,

If I strictly follow the yml file, I would encounter the version conflict error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.1 requires jax>=0.3.15, but you have jax 0.2.19 which is incompatible.
```

The conda install has already installed the latest tf 2.12.*, so the jax version specified in the pip section won't be compatible,  I am trying to figure out if I need to downgrade the tf version, but just want to in the meantime submit this issue in case there's any official guidance.

Thanks in advance,
Frank

**Comment by Jojo109x** [comment]
Thank you very much for pointing this out. I had a lot of troubles with jax and jaxlib. Seemingly so do a lot of new users.
Upgrading jax/jaxlib is not a working solution for me. However, downgrading tensorflow to 2.11.1 does the charm. Maybe this could be updated in the yml file. 
@nrbennet

**Comment by nrbennet** [comment]
Thanks for finding this issue. I have split the conda env into two smaller, easier to install conda envs. Hopefully these cause fewer problems.
