### ISSUE TITLE
GPU error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ning-2022** [nrbennet/dl_binder_design#33]
Hi experts,

>      Thanks for your nice work for binder design.  It's pretty good.  I have attempted to use this code, and I have a question to ask you that when using AF2 predict.py script, it appears some weird information like that" warning: Linking two modules of different target triples: 'LLVMDialectModule' is 'nvptx64-nvidia-gpulibs' whereas '' is 'nvptx64-nvidia-cuda' "  and " Segmentation fault (core dumped)".  I don't know whether the former warning is safe.  And the latter error possibly suggests that the memory of GPU is insufficient.  The GPU I used is RTX 3090, whose memory space is 24GB.  So I think whether there is an option to control the memory using, just like batch option or something I don't know.  Please help me. Your suggestion is very important for me.  Thanks in advance.  

> Sincerely,
> Ning

**Comment by ning-2022** [comment]
I have solved this problem now.  This kind of error was caused by incompatible jax and jax lib. Actually, the author had written them into the yml file for non-expert using.   Thanks again!

All Best,
Ning

**Comment by kenndshi** [comment]
@ning-2022  can you tell how you have solved it?

**Comment by ning-2022** [comment]
Sorry for a delay responding.  I just had adjusted my jax and jaxlib version, like this: 

![Snipaste_2023-08-24_11-01-21](https://github.com/nrbennet/dl_binder_design/assets/107338944/46d8afea-7422-48a8-81b3-75f3deaa18fe)

Goood luck!
Ning
