### ISSUE TITLE
for symmetric multimers

### ISSUE THREAD

**Issue by jongseo-park** [nrbennet/dl_binder_design#36]
Hi,

I generate hexameric multimer using RFdiffusion.

And then, I want to perform validation whether the designed hexameric multimers will be formed as is or not. 

So, I tried to follow the AF2 initial guess protocol mentioned in the supplementary data of the RFdiffusion paper as follows,

```
/opt/tools/dl_binder_design/af2_initial_guess/predict.py -silent des.silent
```

but there was an error like this,

```
Struct with tag run_1_0_mpnn failed in 0 seconds with error: <class 'Exception'>
```

Currently this code is not available for symmetric multimers ?

Sincerely,

Jongseo

**Comment by nrbennet** [comment]
This repository provides scripts which run ProteinMPNN and AF2 for binder design. These scripts will not generalize to larger assemblies, unfortunately. The base functions of these scripts are a nice starting point for writing scripts which will generalize to larger assemblies though!
