### ISSUE TITLE
RuntimeError: jaxlib/cusolver.cc:51: operation cusolverDnCreate(&handle) failed: cuSolver internal error

### ISSUE THREAD

**Issue by SupermeCJ** [nrbennet/dl_binder_design#38]
when i run ` ./af2_initial_guess/predict.py -silent out.silent`, it is error in `RuntimeError: jaxlib/cusolver.cc:51: operation cusolverDnCreate(&handle) failed: cuSolver internal error`.

i try to set `os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = "0.5"`, but it isn't work.

**Comment by nrbennet** [comment]
This is probably an issue related to having an incompatible version of CUDA in your conda environment that does not work with the CUDA Driver you have installed on your system. We provide a CUDA 11.1 compatible env (dl_binder_design.yml) and a CUDA 12 compatible env (af2_binder_design.yml). For other versions of the CUDA driver, you may need to change which CUDA version is installed in the conda env, this can be done by changing the CUDA version in this line of af2_binder_design.yml: - jax[cuda12_pip].
