### ISSUE TITLE
af2_complex_error

### ISSUE THREAD

**Issue by pedrovaliente79** [nrbennet/dl_binder_design#41]
How can i solve this error?
/scratch/valiente/anaconda3/envs/dl_binder_design/lib/python3.9/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.
Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
/scratch/valiente/dl_binder_design/af2_initial_guess/af2_util.py:14: UserWarning: Import of 'rosetta' as a top-level module is deprecated and
 may be removed in 2018, import via 'pyrosetta.rosetta'.
  from rosetta import *
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
WARNING:tensorflow:From /scratch/valiente/dl_binder_design/af2_initial_guess/alphafold/model/tf/input_pipeline.py:151: calling map_fn (from t
ensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
PyRosetta-4 2023 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python39.Release 2023.33+release.9c16e13c3cc4d3ef76e5869e0a
5b44da70cff686 2023-08-18T11:32:04] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
WARNING! No GPU detected running AF2 on CPU
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////

Processing struct with tag: design_ppi_2_dldesign_0_cycle1
The distance between residues 81 and 82 is 54.63 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 81
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_2_dldesign_0_cycle1.pdb fa
iled in 78 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_1_dldesign_0_cycle1
The distance between residues 74 and 75 is 24.13 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 74
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_1_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_4_dldesign_0_cycle1
The distance between residues 91 and 92 is 39.92 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 91
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_4_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_9_dldesign_0_cycle1
The distance between residues 91 and 92 is 55.87 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 91
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_9_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_3_dldesign_0_cycle1
The distance between residues 78 and 79 is 62.85 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 78
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_3_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_0_dldesign_0_cycle1
The distance between residues 95 and 96 is 56.01 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 95
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_0_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_6_dldesign_0_cycle1
The distance between residues 93 and 94 is 30.94 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 93
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_6_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_5_dldesign_0_cycle1
The distance between residues 96 and 97 is 69.17 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 96
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_5_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_7_dldesign_0_cycle1
The distance between residues 71 and 72 is 30.48 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 71
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_7_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>
Processing struct with tag: design_ppi_8_dldesign_0_cycle1
The distance between residues 96 and 97 is 36.09 A > limit 3.0 A.
I'm going to insert a chainbreak after residue 96
Running model_1_ptm
Struct with tag /scratch/valiente/trabajo/2018-2019/Philip_M_Kim/RFdifussion_new_test/protein_mp_fr_out/design_ppi_8_dldesign_0_cycle1.pdb fa
iled in 5 seconds with error: <class 'AttributeError'>

**Comment by pedrovaliente79** [comment]
I add the debug option to my script now I have this error:
File "/scratch/valiente/anaconda3/envs/dl_binder_design/lib/python3.9/site-packages/jax/_src/deprecations.py", line 53, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax' has no attribute 'tree_multimap'
what can I do

**Comment by nrbennet** [comment]
This error is due to having an old version of JAX installed in your environment. I would recommend installing the AF2 environment I have recently added which is easier to install than the previous environment.
