### ISSUE TITLE
runlist no output

### ISSUE THREAD

**Issue by jelka71** [nrbennet/dl_binder_design#42]
Hi, 

According to "dl_interface_design.py --help" it should be possible to select specific pdb-files with the "-runlist" flag. 
Although, I seem to have problems getting an output from this command. 

I run it like this: 

`dl_interface_design.py -pdbdir indir -runlist indir/my.pdb -outpdbdir outdir`

stdout show no errors and finishes after a few seconds, but no output is written to outdir. 

Am I using the syntax wrongly or is this a bug? 

//Jesper

**Comment by nrbennet** [comment]
There is an example of how to run using the `runlist` option here (both scripts use the same definition of a runlist):
`dl_binder_design/examples/example_proteinmpnn_runlist.py`
