### ISSUE TITLE
Is it possible to inpaint a missing part of a protein and designing sequences using the dl_binder_design?

### ISSUE THREAD

**Issue by wangdoc2002** [nrbennet/dl_binder_design#43]
Hi all,

I am inpainting and repairing part of a protein. Previously, this was performed using RFDesign (https://github.com/RosettaCommons/RFDesign). Now the repo suggests using RFdiffusion instead.
So I inpainted 14 residues of a protein using RFdiffusion and generated a bunch of structures. They look beautiful.
Now I need to generate AA sequences of the structures using ProteinMPNN-FastRelax protocol to do sequence design, as suggested by the RFdiffusion repo.

After fed the pdb files to the "dl_interface_design.py", I got error messages like this:
PyRosetta-4 2023 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python39.Release 2023.38+release.52c4cf62073872b07f5cf0623533318b147b5910 2023-09-19T15:49:21] retrieved from: https://urldefense.com/v3/__http://www.pyrosetta.org__;!!K-Hz7m0Vt54!g-kftWD_6n-wmi1E_dFBo61k6nznk11FFjQKUk5LBifU2FiEtos7BqGHbuL4NkDIC2o1zjgBESZeu-qCf1hK6gc$
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
Found GPU will run ProteinMPNN on GPU
Attempting pose: /dssg/home/acct-clsljd/clsljd/bin/RFdiffusion/examples/example_outputs/YbtE/0925/8.pdb
Struct with tag /dssg/home/acct-clsljd/clsljd/bin/RFdiffusion/examples/example_outputs/YbtE/0925/8.pdb failed in 1 seconds with error: <class 'IndexError'>

These are the commands I used to run the program:
module load miniconda3
source activate dl_binder_design

python /dssg/home/acct-clsljd/clsljd/bin/dl_binder_design/mpnn_fr/dl_interface_design.py \
-pdbdir /dssg/home/acct-clsljd/clsljd/bin/RFdiffusion/examples/example_outputs/YbtE/0925
-outpdbdir /dssg/home/acct-clsljd/clsljd/bin/RFdiffusion/examples/Design/YbtE/0925

Thanks for reading this issue thread.

**Comment by nrbennet** [comment]
This repository is specifically designed to work with protein complexes and does not work with protein monomers. You are getting an error related to this. I would suggest looking into ColabFold (https://colab.research.google.com/github/sokrypton/ColabDesign/blob/v1.1.1/rf/examples/diffusion.ipynb) if you would like an easy way to run ProteinMPNN and AlphaFold2 on your designs.
