### ISSUE TITLE
Run dl_binder_design with already generated backbones

### ISSUE THREAD

**Issue by plvdac1** [nrbennet/dl_binder_design#47]
Dear all,
is it possible to run the dl_binder_design pipeline using a backbone and/or a series of sequences already generated with proteinMPNN? How can I input the target pdb if I already have those generated backbone/sequences?

Thanks a lot!

Marco

**Comment by nrbennet** [comment]
Hi Marco, the recommended way to run this pipeline is to generate backbones using RFdiffusion, generate sequences using the ProteinMPNN script provided here, and then running the provided AF2 script on those outputs. If you use this pipeline, everything will just work and you won't have to worry about format. It is possible to get structures which you generated using other methods into this pipeline but that will just require some work on your part
