### ISSUE TITLE
Any reason why cysteine is ommitted by default in ProteinMPNN? Or is that just an accident?

### ISSUE THREAD

**Issue by ackbar03** [nrbennet/dl_binder_design#55]
Hi, 

I noticed the AA Cysteine is omitted by default in the ProteinMPNN design in dl_interface_design.py

`parser.add_argument( "-omit_AAs", type=str, default='CX', help='A string of all residue types (one letter case-insensitive) that you would not like to use for design. Letters not corresponding to residue types will be ignored (default: CX)' )`

https://github.com/nrbennet/dl_binder_design/blob/bfab591db9a70c9c4eaf449c30ce4a1edcb7c989/mpnn_fr/dl_interface_design.py#L64C1-L64C58

Was this left there by accident or is there a reason for this?

Thanks

**Comment by nrbennet** [comment]
Cysteines can yield poorly behaved proteins in some systems so we exclude it by default. Feel free to enable them in your design runs!
