### ISSUE TITLE
Af2_initial_guess question.

### ISSUE THREAD

**Issue by kenndshi** [nrbennet/dl_binder_design#62]
Greetings, and thanks for the job that you have done.
I have run RfDif 10.000 binder designs for my protein. The binder had 10-40 amino acids and I did specify the hotspots, cuz they were experimentally verified. 
I successfully ran the protein mpnn script and got my sequences.
However, after running the predict.py of af2_initial guess my pae_int scores from 10.000 deigns were no less than 27, which according to the paper is considered a bad score.
The thing is that when running af2 it docks my generated binder to completely different and nonscene parts of the receptor protein.
Here I will bring the photos of the generated binder after mpnn and the complex photo after running  af2_intial guess.
![Screenshot 2024-01-05 140345](https://github.com/nrbennet/dl_binder_design/assets/104355001/19f43b35-2183-4b3c-a41a-12fd91a19c0b)
![Screenshot 2024-01-05 140717](https://github.com/nrbennet/dl_binder_design/assets/104355001/2b96170f-32bc-4fe6-ae38-b119ca252d24)

Any ideas on that?

**Comment by nrbennet** [comment]
These high pAE scores should be taken as a prediction by AF2 that these designs will not bind. This does happen sometimes especially when you are targeting a very polar region (I don't know if this is the case for you).

Additionally, 10-40 amino acids is much smaller than the range that we typically use when designing binders. We have found that larger binders (100aa +) are able to have better shape complementarity and generate better contacts with the target. I would for sure try at least in the range of 60-100 in your case.

**Comment by kenndshi** [comment]
> These high pAE scores should be taken as a prediction by AF2 that these designs will not bind. This does happen sometimes especially when you are targeting a very polar region (I don't know if this is the case for you).
> 
> Additionally, 10-40 amino acids is much smaller than the range that we typically use when designing binders. We have found that larger binders (100aa +) are able to have better shape complementarity and generate better contacts with the target. I would for sure try at least in the range of 60-100 in your case.

Thanks for the reply.
One last question.
After doing some research I found that the binders with 50+ aa are usually very expensive. And I want to understand the purpose of setting the binder length from 60-100.
Did you mean that by setting that long binder I can target the hotspot and then shorten my binder length with different techniques?

**Comment by nrbennet** [comment]
I would recommend that you design and order larger binders (60-100aas). What the AF2 step is telling you is that your short designs are not likely to work experimentally.
