### ISSUE TITLE
after af2_initial_guess/predict.py, the distance between binder and target becomes much longer

### ISSUE THREAD

**Issue by rocke2020** [nrbennet/dl_binder_design#79]
Hi @nrbennet 

thanks very much for your shared codes and paper!!
I use RF diffusion to generate, ProteinMPNN-FastRelax, and finally af2_initial_guess, all the default configs.
I test short peptide length 6-10 amino acids, and longer length 26-30 amino acids for the 2 different target proteins.

After run 1000 designs and all the same phenomena:
In the new pdb which is generate from af2 prediction, the distance between binder and target becomes much longer. 
In the pictures blew, the green color is the pdb after ProteinMPNN-FastRelax; the cyan color is the pdb after af2_initial_guess prediction.

Questions:
1. is this noraml or designed on purpose?
in my case, all the pae_interaction are between 22-28, too larger, that's low quality.  When the designed structured from ProteinMPNN-FastRelax is low quality, the distance between binder and target becomes much longer?
2. Maybe some target protein structures are very hard to design good bindiers.
could you supply a target pdb and binder design configs to let me have a pae_interaction < 10 for 1000 designs?
thanks very much in advace!!
thanks for your innovation on af2_initial_guess, a really good idea!!
[pdbs.zip](https://github.com/nrbennet/dl_binder_design/files/15060334/pdbs.zip)

![peptide2](https://github.com/nrbennet/dl_binder_design/assets/34505096/f4fecef5-4150-4cf8-8830-f98484e7d878)
![peptide1](https://github.com/nrbennet/dl_binder_design/assets/34505096/37ad6365-c7a9-4fec-8b7f-7abcaa4e161f)
![屏幕截图 2024-04-22 164109](https://github.com/nrbennet/dl_binder_design/assets/34505096/72fd8534-d532-47b4-a2ec-e65aa4aeb46a)

**Comment by Dan-Burns** [comment]
@rocke2020, did you find an answer to this?
